services:
  
  # Service for the database
  database:
    container_name: postgresql_database
    image: postgres
    restart: always
    ports:
      - 8080:5432
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

  # Service for the pgadmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      [database]

  # Application service
  app:
    container_name: app
    build: .
    # command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    
    volumes:
      - .:/app

    ports:
      - 8000:8000
    depends_on:
      [database]

    restart: always