"""initial3

Revision ID: a9d1c64b68c3
Revises: f4965faee6e4
Create Date: 2023-05-14 12:02:14.190374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9d1c64b68c3"
down_revision = "f4965faee6e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
