name: Format code using Black

on:
  push:
    branches: "**"

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Check formatting with Black
        run: |
          pip install black
          black .